AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: local
    #AllowedValues:
    #  - local
    #  - dev
    #  - prod
    AllowedPattern: "^local$|^dev$|^prod$|^feature-[a-zA-Z0-9_-]+$"
    Description: "The deployment environment"

Metadata: &esbuild_props
    Format: esm
    Minify: true
    Target: es2022
    #Packages: external
    OutExtension:
          - .js=.mjs
    External:
      - "@aws-sdk/client-dynamodb"
      - "@aws-sdk/lib-dynamodb"

Resources:
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getAllItems/getAllItems.getAllItemsHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the Table
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          DYNAMO_DB_ENDPOINT: ""
          DB_TABLE: !Sub Sample-${Environment}
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:        
        <<: *esbuild_props
        EntryPoints:
          - src/handlers/getAllItems/getAllItems.mts

  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getById/getById.getByIdHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        HTTP get method to get one item by id from a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          DYNAMO_DB_ENDPOINT: ""
          DB_TABLE: !Sub Sample-${Environment}
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild_props
        EntryPoints:
          - src/handlers/getById/getById.mts

  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putItem/putItem.putItemHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description:
        HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Environment:
        Variables:
          DYNAMO_DB_ENDPOINT: ""
          DB_TABLE: !Sub Sample-${Environment}
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        <<: *esbuild_props
        EntryPoints:
          - src/handlers/putItem/putItem.mts

  # DynamoDB table to store item: {id: &lt;ID&gt;, name: &lt;NAME&gt;}
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "Sample-${Environment}"
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  #HttpApi:
  #  Type: AWS::Serverless::HttpApi
  #  Properties:
  #    StageName: !Ref Environment

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
